### ISSUE TITLE
Make it presentable

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/foxsi-4matter#12]
### Goal

To send the package to IPMU, with documentation, so they can build for their Raspberry Pi to help with CdTe DE development. Also helpful context when IPMU writes the macro command to SpW byte array map.

### Todo

- [ ] Finish #8.
- [ ] Add doxygen comments.
- [x] Rename `PepperMill`.
- [ ] Add some readme or PDF docs for the layer architecture and authorship responsibilities.
- [ ] Add _basic_ interface to [Yuasa RMAP library](https://github.com/yuasatakayuki/SpaceWireRMAPLibrary).
- [ ] Add template `.h` for the macro command => SpW byte array map.

**Comment by thanasipantazides** [comment]
Closing. This is obsolete.
