### ISSUE TITLE
Integrate `UARTPort`

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/foxsi-4matter#42]
### Status

There is a lovely [UART interface here](https://github.com/foxsi/foxsi-4matter/blob/main/include/UARTInterface.h). It needs to be integrated in the flight software.

There are two other places UART-related work is done in the code.
1. A [`UART`](https://github.com/foxsi/foxsi-4matter/blob/616f58aadf788df7900dc24835431ffc9b76031b/include/DataLinkLayer.h#L197) object holds limited, runtime-constant configuration data on the UART link.
2. [`TransportLayerMachine`](https://github.com/foxsi/foxsi-4matter/blob/616f58aadf788df7900dc24835431ffc9b76031b/include/TransportLayer.h#L22) manages all the network operations onboard (Ethernet-to-Ethernet communication, Ethernet-to-buffer, SpaceWire-to-buffer, etc). This class will need to expose the UART interface implemented in `UARTPort`.

### Todo

- [x] Kris think about a better naming scheme so `UARTPort` and `UART` are less confusing. Honestly `UARTPort` seems fine, it's `UART` that is totally generic and unclear.
- [ ] Kris add a new constructor to `UARTPort` that takes a reference to a [`UART`](https://github.com/foxsi/foxsi-4matter/blob/616f58aadf788df7900dc24835431ffc9b76031b/include/DataLinkLayer.h#L197), plus `vtime` argument (I think we initialize `vmin` as default then modify it on-the-fly using command-specific size data).
    - for background here, I generate `UART` objects from JSON configuration data on startup, so that's a convenient way to hand you the information.
- [x] Kris modify TransportLayer.h adding a field with a reference to a `UARTPort` and modifying each constructor:
```C++
class TransportLayerMachine {
    // ...
    UARTPort& uart_port;
    TransportLayerMachine(... , UARTPort& port, boost::asio::io_context& context)
    // ...
};
```
- [x] Kris modify TransportLayer.cpp implementing the `TransportLayerMachine` constructors. You should initializer `TransportLayerMachine::uart_port` using initializer list syntax as is done for the `io_context` objects.
- [x] Then, Thanasi add UART-specific methods to TransportLayerMachine.
