### ISSUE TITLE
Add capability to verify SpaceWire RMAP write commands

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/foxsi-4matter#53]
### The issue
During testing Dec 17 2023 with 4 CdTe canisters reading out, we find that write commands may fail to register in the DE. Root cause could be the same as the SDRAM access conflict issue in the SPMU. The effect visible to the Formatter is that all ring buffer write pointers lock to `0000-0000` because DE Standby mode or DE Observation mode are never activated. To mitigate, we should verify success of write commands, and repeat failed write commands.

#### The gnarly part
Some write commands are more important to retry than others. Write command retry should not block during flight (use case: uplink command to one system should not inhibit all others). In some situations write commands are a critical part of the sequence (e.g. starting observation); in others write commands are for convenience (e.g. notify shutter door open). It will be challenging to integrate command priority information this late in the development.

### Todo
- [x] Write a small script that runs on Formatter, accepts 2 byte input strings (`std::cin`), looks up command (`CommandDeck::get_command_bytes_for_sys_for_code()`), and sends it. Use this to validate RMAP write-with-reply (instruction `0x7d`) responses from SPMU.
- [x] Discuss the implementation and priority command list with the team. Consider flight FMEA.
- [x] Add to `TransportLayerMachine::sync_tcp_send_command_for_sys()`: there is one `if` statement conditioned on `cmd.read`. Add another in series like this:
```C++
if (sys_man.system.spacewire) {
    if ((sys_man.system.type == COMMAND_TYPE_OPTIONS::SPW) && (cmd.get_spw_instruction() & 0x80)) {
        // do write and expect reply
    }
}
```
- [x] Implement retry based on discussion.
